### ISSUE TITLE
BSL Language Server - Use configuration file: auto

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/sonar-bsl-plugin-community#104]
![image](https://user-images.githubusercontent.com/729213/85207781-e67ee000-b333-11ea-8b9e-80fb0f03b5cc.png)

Предусмотреть третий вариант **auto** (по-умолчанию).
В случае, если файл **.bsl-language-server.json** найден в корневой директории git использовать его, в противном случае использовать профиль сонара.

**Comment by asosnoviy** [comment]
Кажется on по дефулту будет вести себя также.

**Comment by zeegin** [comment]
Сейчам по дефолту когда я создал проект и поместил в репу файл с конфигом то профиль будет сонара, а нужно чтоб если был файл конфига то профиль был по конфигу.

**Comment by asosnoviy** [comment]
Я имел ввуду если сделать Override вкл по дефолту

**Comment by zeegin** [comment]
А что будет если файл не найден?

**Comment by asosnoviy** [comment]
> А что будет если файл не найден?

Надо проверить, но думаю что ничего.

**Comment by nixel2007** [comment]
Если файла нет, но настройка включена, то будет браться конфиг из профиля качества с еррор сообщением в лог

**Comment by zeegin** [comment]
Т.е. достаточно изменить значение по-умолчанию?

**Comment by nixel2007** [comment]
Да, но я не уверен, что нужно :) ты же, когда заказывал эту опцию, наоборот говорил чтобы она была выключена по умолчанию.

Но у себя ты можешь включить её, да. Если еггоги в логах не смущают

**Comment by zeegin** [comment]
Не понятно пока как лучше.
Давай оставим пока ищью, пусть повисит и еще пользователи отпишутся.

**Comment by theshadowco** [comment]
4 года... думаю никто не отпишется :)
