### ISSUE TITLE
Cannot find '.class' file for class bsl.languageserver.context.infrastructure.DocumentContextConfiguration

### ISSUE THREAD

**Issue by Otkrick** [1c-syntax/sonar-bsl-plugin-community#116]
On stage:
`01:15:40.719 INFO: Source dir: /opt/projects/project-01/src
01:15:41.147 DEBUG: Creating shared instance of singleton bean 'serverContext'
01:15:41.179 DEBUG: Finding files to populate context...
01:15:41.925 DEBUG: Populating context...
`
hangs:
`01:15:41.951 DEBUG: Creating shared instance of singleton bean 'documentContextConfiguration'
01:15:41.952 DEBUG: Cannot find '.class' file for class [class com.github._1c_syntax.bsl.languageserver.context.infrastructure.DocumentContextConfiguration$$EnhancerBySpringCGLIB$$ec3acc1c] - unable to determine constructor/method parameter names
01:15:41.953 DEBUG: Autowiring by type from bean name 'documentContextConfiguration' via constructor to bean named 'org.springframework.context.annotation.AnnotationConfigApplicationContext@4403bff8'
01:15:41.961 DEBUG: Creating shared instance of singleton bean 'diagnosticComputer'`

JDK versions:
`
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-post-Debian-1deb10u1, mixed mode, sharing)

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1, mixed mode, sharing)
`

**Comment by Otkrick** [comment]
also with:
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by nixel2007** [comment]
Hello! Thanks for report!
We'll try to investigate and fix that problem. Other users face this issue time to time

**Comment by nixel2007** [comment]
There is no more DocumentContextConfiguration class in upstream BSL Language Server.
Feel free to post new issue if something simillar to this bug will ocure.
