### ISSUE TITLE
Невозможно задать свойство sonar.bsl.languageserver.skipSupport через файл sonar-project.properties

### ISSUE THREAD

**Issue by artbear** [1c-syntax/sonar-bsl-plugin-community#117]
И в итоге фактически его можно задать только 
- через настройки проекта на сервере СонарКуб
- или сделать спец. json-файл для bslls

что не всегда удобно

Обсуждали с @nixel2007 на недавнем митапе Инфостарте (в ноябре)

фактически получается нестыковка - свойство есть, а в файле задать нельзя (

**Comment by nixel2007** [comment]
хорошо бы уточнить, какие варианты для значения свойства передавались. с пробелами или без, и что было в логах и сканер-контексте. :)

**Comment by artbear** [comment]
я детали точно не вспомню, но я пробовал и с пробелами, и без них (аналогично значению перечисления в json)

сразу выдавалась ошибка на наличие параметра (
