### ISSUE TITLE
Ошибка при анализе проектов dotnet

### ISSUE THREAD

**Issue by otymko** [1c-syntax/sonar-bsl-plugin-community#118]
![image](https://user-images.githubusercontent.com/11651847/102118747-b774a180-3e72-11eb-9d40-028c62018567.png)

**Comment by itsecforu** [comment]
Так все же написано в логе про символ

**Comment by nixel2007** [comment]
@otymko а ты это разве в прошлый раз (с пробелами в sources) не пофиксил? или это какой-то соседний кейс?

**Comment by otymko** [comment]
@nixel2007 нет, это не помогло. Хотел отловить через дебаг, но как-то пока не сложилось

**Comment by theshadowco** [comment]
не актуально, у меня .net и прочие нормально собираются при наличии bslls
