### ISSUE TITLE
Generic rule регистратор

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/sonar-bsl-plugin-community#13]
Компонент, который будет загружать описания правил из файла json/xml, аналогичный штатному сонаровскому импортеру xml-описаний.

пропертя с путями к файлам описаний.

**Comment by otymko** [comment]
@nixel2007 беру в работу

**Comment by otymko** [comment]
#39

**Comment by qtLex** [comment]
Наверное, стоит закрыть.
