### ISSUE TITLE
Доработать пакетирование правил для edt

### ISSUE THREAD

**Issue by ivanmolodec** [1c-syntax/sonar-bsl-plugin-community#149]
Библиотека stebi позволяет выгружать диагностики EDT в SonarQube. На данный момент поддерживается только generic issues, но если будет реализована поддержка выгрузки в .json формат BSL LS в плагине необходимо доработать возможность обработки таких файлов с ключом репозитория "edt" и ключом проверки в формате из stebi
https://github.com/Stepa86/stebi/issues/6

**Comment by ivanmolodec** [comment]
Или сделать ключ "synthetic", чтобы в перспективе туда и синтаксис чек конфигуратора подсовывать

**Comment by theshadowco** [comment]
пока нормально отрабатывает костыль, в котором едт мимикрирует под АПК

**Comment by nixel2007** [comment]
@theshadowco какой костыль? как generic issue, получаемый от stebi, превратить в правила апк? и в какие именно?

**Comment by theshadowco** [comment]
кароч, скоро будет
