### ISSUE TITLE
Добавление авторов кода.

### ISSUE THREAD

**Issue by AlekseyAkifev** [1c-syntax/sonar-bsl-plugin-community#151]
Добрый день. Плагин может может кроме самого кода еще заполнять авторов кода для сонара? 
Есть ли возможность прописать в каких то файлах настроек: ПользовательХранилища = ПользовательSоnar. Что бы было сопоставление? 
Бьюсь 2 неделю с указанием авторства кода в сонар, перерыл всю информацию на инфостарте и не только. Буду очень благодарен за подробный ответ.

**Comment by nixel2007** [comment]
Добрый день. Сонар берет информацию об авторе строчки кода из вывода git blame.
Чтобы в гит-репозитории были корректные авторы, попробуйте использовать https://github.com/oscript-library/gitsync или https://github.com/1C-Company/GitConverter
