### ISSUE TITLE
При загрузке в сонар документации к проверке для ссылки заменяется # на =

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/sonar-bsl-plugin-community#16]
https://github.com/1c-syntax/bsl-language-server/blob/develop/docs/diagnostics/NumberOfParams.md

![image](https://user-images.githubusercontent.com/729213/56393339-d0135b00-623c-11e9-8b40-ae3b6beda36f.png)

![image](https://user-images.githubusercontent.com/729213/56393273-99d5db80-623c-11e9-965b-a13202eb8899.png)

**Comment by nixel2007** [comment]
Есть такое. Сделано ради поддержки нестандартного сонаровского форматтера маркдауна. Но в ссылках такой замены быть не должно, согласен.

**Comment by zeegin** [comment]
https://github.com/1c-syntax/sonar-bsl-plugin-community/blob/master/src/main/java/com/github/_1c_syntax/sonar/bsl/language/BSLLanguageServerRuleDefinition.java#L108

```java
replaceAll("(?!.+\\[)#(?!.+\\])", "=")
```

**Comment by nixel2007** [comment]
@zeegin а ты уверен в своей регулярке? что-то у меня возникли сомнения:

https://regex101.com/r/Tc1mg6/1

**Comment by atai** [comment]
Тоже самое с правилом "Приведение к числу в попытке" - ссылка на стандарт не открывается (er 404)
