### ISSUE TITLE
Работа SonarQube Scanner прерывается сообщением Read timed out

### ISSUE THREAD

**Issue by VladFrost** [1c-syntax/sonar-bsl-plugin-community#17]
```
17:01:18  ERROR: Error during SonarQube Scanner execution
17:01:18  ERROR: Fail to request http://er258-ci-1.tc.test:9000/api/ce/submit?projectKey=sbm&projectName=sbm
17:01:18  ERROR: Caused by: timeout
17:01:18  ERROR: Caused by: Read timed out
```

При этом фоновое задание в SonarQube Server всё равно стартует и анализ продолжается.

**Comment by asosnoviy** [comment]
@VladFrost не полечилось? тут наткнулся на `sonar.ws.timeout` тут https://docs.sonarqube.org/latest/analysis/analysis-parameters/

**Comment by VladFrost** [comment]
С переходом на новый плагин больше не воспроизводится.
