### ISSUE TITLE
Локализация интерфейсных строк плагина

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/sonar-bsl-plugin-community#175]
Сейчас строки не переводятся плагином-руссификатором. Надо подумать, как и что доработать, чтобы решить эту проблему.

**Comment by nixel2007** [comment]
Плагин может поставлять ru-бандл с переводами. Но насколько я помню, настройки нельзя перевести вообще.

**Comment by theshadowco** [comment]
ну другие настройки то мы переводим, те, что не в плагинах. В общем, надо посмотреть

**Comment by nixel2007** [comment]
Разве? Кажется, только заголовки групп настроек. А сами настройки нет. В общем, надо проверить
