### ISSUE TITLE
Удаление плагина из administration-marketplace

### ISSUE THREAD

**Issue by itsecforu** [1c-syntax/sonar-bsl-plugin-community#209]
Привет всем, я пытаюсь добавить плагин. 

Мне нужна версия 1.10.0, но на в дашборде отображается 1.11.0, хотя ее нет в папке plugins.

При нажатии install `Error while downloading plugin 'communitybsl' with version '1.11.0'. No compatible plugin found.`

Добавление 1.10.0 в папку ничего не меняет.

Как удалить этот хэш или что-то подобное и маркета?

Его также нет в папке `extensions_save/plugins.`

тут тоже пусто `/opt/sonarqube/lib/bundled-plugins `

**Comment by nixel2007** [comment]
Какая версия SQ?

**Comment by itsecforu** [comment]
Community EditionVersion 8.1 (build 31237)

**Comment by nixel2007** [comment]
у версии 1.11 минимальная поддерживаемая версия - 8.9

**Comment by nixel2007** [comment]
Но если совсем уж нужна 1.10 возьмите ее напрямую из релизов https://github.com/1c-syntax/sonar-bsl-plugin-community/releases/tag/v1.10.0

**Comment by itsecforu** [comment]
да я пытаюсь 1.10 добавить, но в даше следы 1.11 , и я не знаю как удалить оттуда

**Comment by nixel2007** [comment]
Покажите скрин

**Comment by itsecforu** [comment]
https://aws1.discourse-cdn.com/sonarsource/uploads/sonarcommunity/original/3X/a/1/a1aaf12256a446feaf99904f027adcb1d4d44259.png

https://aws1.discourse-cdn.com/sonarsource/uploads/sonarcommunity/original/3X/d/0/d043fc57f4dad53ec855281a054962eb93950ad8.png

**Comment by nixel2007** [comment]
Я понял. В маркетплейсе сейчас доступен только плагин 1.11, так как все старые версии они удалили после выхода lts. Из магазина вы плагин на старый сервер не поставите, подкладывайте нужный жарник в каталог руками.

**Comment by itsecforu** [comment]
Если плагин руками положить, sonarube не поднимается после ребута. При удалении нормально загружается.

**Comment by theshadowco** [comment]
а что в логах пишет?

**Comment by itsecforu** [comment]
> Reference in ne

По плагину вообще ничего не нашел, и даже не виду его упоминаний в файловой системе.

**Comment by nixel2007** [comment]
> Если плагин руками положить, sonarube не поднимается после ребута. При удалении нормально загружается.

Давайте логи
