### ISSUE TITLE
NullPointerException при использовании sonar.externalIssuesReportPaths

### ISSUE THREAD

**Issue by otymko** [1c-syntax/sonar-bsl-plugin-community#21]
На самых последних версиях у меня почему-то не работает загрузка issues из внешних источников (externalIssuesReportPaths).
![image](https://user-images.githubusercontent.com/11651847/60703005-c25f9e80-9f2a-11e9-9505-8e7867ac6cf4.png)
в sonar-project.properties использую:
![image](https://user-images.githubusercontent.com/11651847/60703023-d3a8ab00-9f2a-11e9-978f-ff9771b9e640.png)
Дано:
* sonar-scanner-cli-4.0.0.1744
* sonar 7.9.0.26994
* community plugin sonar 0.5.1+2.dev

**Comment by otymko** [comment]
P.S. проверку делаю на типовой конфе Документооборот 8 КОРП, редакция 2.1 (2.1.12.2)

**Comment by asosnoviy** [comment]
А кинь файлик плз

**Comment by otymko** [comment]
[bsl-json.zip](https://github.com/1c-syntax/sonar-bsl-plugin-community/files/3361439/bsl-json.zip)

**Comment by otymko** [comment]
@asosnoviy конфу надо?

**Comment by asosnoviy** [comment]
Не пока не надо.

**Comment by otymko** [comment]
Вопрос снят. API работает. Для отчетов в формате json используется свойство sonar.bsl.languageserver.reportPaths
