### ISSUE TITLE
Deploying to the Marketplace

### ISSUE THREAD

**Issue by otymko** [1c-syntax/sonar-bsl-plugin-community#23]
Публикация на маркетплейсе Sonar.

- [x] Проверить лицензию. Разрешенные http://opensource.org/licenses
- [x] Опубликовать проект на GitHub Pages
- [x] Перевести документацию на английский
- [x] Проверить/создать ключ проекта по требованиям https://docs.sonarqube.org/latest/extend/deploying-to-marketplace/
- [x] Должна проходить проверка качества проекта на sonarcloud. Вытекающая задача - покрытие кода более 80%
- [x] Изменить имя артефакта (jar) на `sonar-{pluginKey}-plugin`
- [x] If your plugin adds analysis of a language which is not analyzed by any SonarSource analyzer you must provide the NCLOC and NCLOCDATA metrics, which are both required to make the user experience within SonarQube consistent. You can take a look at how those metrics are provided by SonarJava (NCLOC, [NCLOCDATA](https://github.com/SonarSource/sonar-java/blob/4cb1065f405edccbb7d229633945b3c56aeab04c/java-frontend/src/main/java/org/sonar/java/ast/visitors/FileLinesVisitor.java#L101))
- [x] Таргет на релизный BSL LS
- [x] Выпустить релиз сонар-плагина
- [x] Создать тему на форуме о включение плагина в маркетплейс
- [x] PR информации о плагине в sonar-update-center-properties

Все официальная информация о публикации https://docs.sonarqube.org/latest/extend/deploying-to-marketplace/

**Comment by nixel2007** [comment]
1) Плагин лицензируется под LGPLv3, как и большинство сонаровских плагинов.

**Comment by nixel2007** [comment]
4 ключ плагина изначально делался по гайд-лайнам https://github.com/1c-syntax/sonar-bsl-plugin-community/blob/master/build.gradle#L91

**Comment by otymko** [comment]
2. сайт опубликован через GitHub Pages

**Comment by otymko** [comment]
5. Покрытие теперь больше 80 процентов

**Comment by otymko** [comment]
3. Документация залита в master

**Comment by nixel2007** [comment]
Заменил artifactId

**Comment by otymko** [comment]
@nixel2007  а смена артифактИд не сулит проблемами при обновлении плагина?

**Comment by nixel2007** [comment]
@otymko проверил на локальной установке, все в норме.

**Comment by nixel2007** [comment]
там основная завязка на pluginKey, а он не меняется.там основная завязка на pluginKey, а он не меняется.

**Comment by nixel2007** [comment]
Линк на пулл-реквест: https://github.com/SonarSource/sonar-update-center-properties/pull/35

**Comment by nixel2007** [comment]
Линк на тред: https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-0-0/12165

**Comment by otymko** [comment]
mission is complete

**Comment by asosnoviy** [comment]
Заводи новый ишуз с рекомендациями от Ann

**Comment by theshadowco** [comment]
Поздравляю!

**Comment by theshadowco** [comment]
![image](https://user-images.githubusercontent.com/9591731/61930433-5e0e8880-af86-11e9-8b4a-21ff09b363e3.png)

**Comment by nixel2007** [comment]
Перенес замечания из https://community.sonarsource.com/t/new-release-1c-bsl-community-plugin-1-0-1/12165/8?u=nixel2007 в виде ишузов.
