### ISSUE TITLE
Ложное срабатывание "Обращение к виртуальной таблице без параметров" на таблице критерия отбора

### ISSUE THREAD

**Issue by BarinovIN** [1c-syntax/sonar-bsl-plugin-community#255]
Пример приведён на снимке экрана. У виртуальной таблицы всего один параметр и он установлен.
Непонятно что нужно исправить в этом запросе.

![image](https://user-images.githubusercontent.com/65981489/218663866-c4ecca47-0804-40b3-ba78-f9ae2d4654ad.png)

SQ: 8.9.10.61524
Plugin: 1.11.0

**Comment by nixel2007** [comment]
Спасибо, это уже репортили в репозитории bsl-language-server.
