### ISSUE TITLE
Проблема с анализом результатов выгрузки ошибок из АПК

### ISSUE THREAD

**Issue by dentaky** [1c-syntax/sonar-bsl-plugin-community#277]
SonarQube Версия 8.9.9 (build 56886)
1C (BSL) Community Plugin v 1.11.0

Выполняю анализ конфигурации УПП. Результат для Сонара формирую обработкой acc-export в формате reportjson.

Пример срабатывания на модуле Reports/ДРП2014/Ext/ObjectModule.bsl

Есть результат первого анализа кода УПП (конфигурация версии 1000):

"range": {
"start": {
"line": 12891,
"character": 1
},
"end": {
"line": 12891,
"character": 25
}
},
"severity": "Error",
"code": "247",
"source": "acc-rules",
"message": "Имена переменных не должны состоять из одного символа.\nм = тз.НайтиСтроки(отб);  \nhttps://its.1c.ru/db/v8std#content:454:hdoc  \nhttps://its.1c.ru/db/v8std#content:454:hdoc  \n",
"relatedInformation": null

Ошибка регистрируется корректно от автора 2021 года.

Второго (конфигурация версии 1001):

"range": {
"start": {
"line": 12891,
"character": 1
},
"end": {
"line": 12891,
"character": 25
}
},
"severity": "Error",
"code": "247",
"source": "acc-rules",
"message": "Имена переменных не должны состоять из одного символа.\nм = тз.НайтиСтроки(отб);  \nhttps://its.1c.ru/db/v8std#content:454:hdoc  \nhttps://its.1c.ru/db/v8std#content:454:hdoc  \n",
"relatedInformation": null

Ошибка остается на старом месте в 21-м году.

И третьего (конфигурация версии 1002), где программист вносит изменения в модуль на 6 строчек.

В результате ошибка смещается вниз на кол-во строк, которые внес программист выше:

"range": {
"start": {
"line": **12897**,
"character": 2
},
"end": {
"line": **12897**,
"character": 25
}
},
"severity": "Error",
"code": "247",
"source": "acc-rules",
"message": "Имена переменных не должны состоять из одного символа.\nм = тз.НайтиСтроки(отб);  \nhttps://its.1c.ru/db/v8std#content:454:hdoc  \nhttps://its.1c.ru/db/v8std#content:454:hdoc  \n",
"relatedInformation": null

И Сонар регистрирует эту ошибку как новую после третьего анализа, т.к. строки в модуле изменились:
 
<a href="https://ibb.co/dmN6TJN"><img src="https://i.ibb.co/dmN6TJN/image.png" alt="image" border="0"></a>

До изменений модуля она была корректно зарегистрирована в 2021 году:

<a href="https://ibb.co/GFDppTF"><img src="https://i.ibb.co/GFDppTF/image.png" alt="image" border="0"></a>

И таких ошибок появляется в анализе очень много по любым конфигурациям именно по анализу АПК:

<a href="https://ibb.co/1fh2NZd"><img src="https://i.ibb.co/1fh2NZd/image.png" alt="image" border="0"></a>

Все 30 штук являются ошибками старых периодов, но из-за смещения строк в модулях, они перерегистрируются как новые, чего быть не должно:

<a href="https://ibb.co/d5r9QZQ"><img src="https://i.ibb.co/d5r9QZQ/image.png" alt="image" border="0"></a>

При этом встроенные правила плагина bsl не дают такого поведения и если модуль изменился, то все ошибки 21 года остаются на старом месте:

<a href="https://ibb.co/3R6ZnnC"><img src="https://i.ibb.co/3R6ZnnC/image.png" alt="image" border="0"></a>

**Comment by nixel2007** [comment]
Вроде обсудили же в чате, что дело не в смещении номеров строк, а изменении самих строк (смена количества табов).
