### ISSUE TITLE
Как создавать свое правило проверки? 

### ISSUE THREAD

**Issue by khorevaa** [1c-syntax/sonar-bsl-plugin-community#3]

**Comment by nixel2007** [comment]
Диагностики создаются в рамках проекта https://github.com/1c-syntax/bsl-language-server
Подробный гайд по написанию диагностик в планах

**Comment by nixel2007** [comment]
https://github.com/1c-syntax/bsl-language-server/wiki/%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%B8%D0%B0%D0%B3%D0%BD%D0%BE%D1%81%D1%82%D0%B8%D0%BA%D0%B8
