### ISSUE TITLE
Java 8?

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/sonar-bsl-plugin-community#34]
Подумать, обсудить. "И хочется и колется".
лично мне пока хочется больше, чем колется, но в условиях работы ЕДТ исключительно на java8 и будущей статьи @Stepa86...

**Comment by asosnoviy** [comment]
Я тут не совсем понял... 4й Сканер же хотел 11ю

**Comment by nixel2007** [comment]
Но третий все еще работает.

**Comment by Stepa86** [comment]
4ый у меня тоже работал на 8ой, пока плагин не обновил.

Подмена `JAVA_HOME `перед пуском сканера помогла

**Comment by nixel2007** [comment]
> 4ый у меня тоже работал на 8ой, пока плагин не обновил.

а вот это любопытно о_О

**Comment by asosnoviy** [comment]
Хм... А может он только намекал, что пора 11....
