### ISSUE TITLE
Анализ падает при работе с эмодзи 

### ISSUE THREAD

**Issue by dzaurov** [1c-syntax/sonar-bsl-plugin-community#348]
Анализ падает при работе с более новыми и сложными эмодзи. Ниже приведу пример эмодзи, на котором анализ будет падать и пример эмодзи на котором анализ падать не будет.

🟡 — кодировка требует 4 байта, т.к. находится в SMP (Plane 1).
✅ — укладывается в 3 байта, т.к. находится в BMP (Plane 0).

Не знаю в чем причина, но видимо, где то используется старая версия UTF-8. Например, в MySQL есть utf8mb4 (новое, поддерживает SMP) и utf8mb3 (старое, не поддерживает SMP).

[Test.bsl.txt](https://github.com/user-attachments/files/17946891/Test.bsl.txt)
[ЛогОшибки.txt](https://github.com/user-attachments/files/17946795/default.txt) 
P.S. Лог от другого модуля, поэтому номера строк не совпадают с приложенным тестовым модулем.

**Comment by nixel2007** [comment]
Починиль.
