### ISSUE TITLE
Документация по развертыванию

### ISSUE THREAD

**Issue by ruimage** [1c-syntax/sonar-bsl-plugin-community#4]
Добавьте пожалуйста пример и инструкцию по развертыванию

**Comment by nixel2007** [comment]
Как и любой сонар плагин - скачать jar, положить в папку с плагинами. Или я неправильно понимаю вопрос? 
Выход в маркетплейс в планах.

**Comment by nixel2007** [comment]
Начал накапливать простую документацию в Readme репозитория. Чуть позже опишу возможности плагина здесь и документацию по запуску bsl language server в его репе
