### ISSUE TITLE
Ошибка сканера на не 1С проектах при установленном плагине 1С BSL

### ISSUE THREAD

**Issue by DMDone** [1c-syntax/sonar-bsl-plugin-community#40]
Наличие установленного на сервере плагина 1С BSL приводит к ошибке сканера на проверке **не 1С проектов** при несовместимой с 1C плагином версии Java на клиенте,

Исходные:
1) на клиенте - java version "1.8.0_221"
2) на сервере openjdk version "11.0.4"
3) плагин 1С BSL **не установлен**
Проект c# (не 1C) - анализ проходит успешно:

> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION SUCCESS
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 54.658s
> INFO: Final Memory: 12M/63M
> INFO: ------------------------------------------------------------------------
> The SonarQube Scanner has finished
> 09:58:50.858 Post-processing succeeded.

Устанавливаем из магазина плагин 1С BSL.
Проверяем тот же c# проект (не 1С) получаем ошибку:

> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 4.829s
> INFO: Final Memory: 4M/15M
> INFO: ------------------------------------------------------------------------
> ERROR: Error during SonarQube Scanner execution
> ERROR: The plugin [communitybsl] does not support Java 1.8.0_221
> ERROR: Caused by: com/github/_1c_syntax/sonar/bsl/BSLPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> ERROR:
> The SonarQube Scanner did not complete successfully
> 10:17:13.23 Post-processing failed. Exit code: 1

**Comment by nixel2007** [comment]
Добрый день.

Сонар-сканер перед началом своей работы загружает все плагины, установленные на сервере, которые могут запускаться на стороне сканера. В начале анализа выполняется проверка всех файлов проектов, определение их расширений и привязка к конкретным компонентам внутри плагинов. Для этого все эти плагины должны как минимум проинициализироваться.

Плагин для 1С требует java11, так же как и сервер sonarqube и так же как и начнет требовать sonar-scanner (в обозримом будущем). Sonar-scanner 4.0 уже поставляется с jre11 на борту

Так что единственным решением этой проблемы является установка java11 на машину и/или обновление сонар-сканнера.
