### ISSUE TITLE
Настройка для исключения объектов конфигурации из конфигурации поставщика

### ISSUE THREAD

**Issue by ovcharenko-di** [1c-syntax/sonar-bsl-plugin-community#47]
Нужна возможность указать настройку в sonar-project.properties, чтобы:

- исключать из проверки все объекты метаданных из конфигурации поставщика на замке
- исключать из проверки все объекты метаданных из конфигурации поставщика с любыми правилами поддержки

при отсутствии настройки проверяются все объекты.

**Comment by zeegin** [comment]
@nixel2007 А такую настройку при загрузку для genericIssue применять можно будет применять? Или через мягкий загрузчик дженериков из плагина?

**Comment by nixel2007** [comment]
@zeegin нет. generic issue управляется ядром сонара, мы никак на него повлиять не можем. плюс вроде уже решили, что эта доработка будет на стороне BSL LS

**Comment by zeegin** [comment]
@nixel2007 @otymko Ну давайте подумаем: если я хочу исключать объекты на поддержке, я хочу их исключать из всех источников, а не только из BSL-LS. Допустим с EDT - все хорошо - они там сами будут отключаться - это поведение по умолчанию для EDT. А для АПК и других? Надо в каждом механизме свой фильтр делать или фильтровать через механизм Антона?

Может быть в сам BSL сделать загрузчик сторонних результатов, а он уже их отфильтрует и выведет? 
Так, например, можно будет в VSCode делать просмотр не только результатов BSL но и EDT и АПК.

**Comment by nixel2007** [comment]
@zeegin ты не забывай, что даже если в сонаре не используется диагностик-провайдер из BSL LS, он все равно выполняет полный парсинг. Как следствие будет информация о метаданных и о файлах на поддержке.

Можно написать свой загрузчик из GenericIssue, но может проще и логичнее научить АПК выгружать в json-формате?

**Comment by otymko** [comment]
Связанная задача https://github.com/1c-syntax/bsl-language-server/issues/537
