### ISSUE TITLE
Ограничение верхнего предела когнитивной сложности

### ISSUE THREAD

**Issue by pimchest** [1c-syntax/sonar-bsl-plugin-community#49]
Было бы не плохо игнорировать модули у которых сложность при проверке превышает например 500, т.к. они скорее всего она никогда не будет устранена и сделана преднамеренно в следствии сложности механизма и и предметной области.
![image](https://user-images.githubusercontent.com/32355274/64685283-63208c00-d48f-11e9-8af5-2a042c39441a.png)

[https://github.com/1c-syntax/bsl-language-server/issues/349](url)

**Comment by nixel2007** [comment]
Здесь это лишнее, а в бсл лс оставлю.
