### ISSUE TITLE
Уменьшение размера jar-файла

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/sonar-bsl-plugin-community#59]
copy 1c-syntax/bsl-language-server#556

>Сейчас внутри жарника есть много лишней требухи (открыть как зип архив и удивиться). JUnit, c# рантайм ANTLR и прочее.Надо пройтись по зависимостям и сделать exlude лишнего.

**Comment by nixel2007** [comment]
Большая часть уменьшения прошла от уменьшения BSL LS и MdClasses. Зависимости сонар-плагина в норме
