### ISSUE TITLE
В таблицы параметров неправильно вставляются символы `|` 

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/sonar-bsl-plugin-community#62]
![image](https://user-images.githubusercontent.com/1132840/68868945-70fdc200-0709-11ea-9ea1-ec4adc905f09.png)

Видимо, надо их заэкранировать

**Comment by theshadowco** [comment]
это конвертер сонара. 

Чтобы не забыть - надо попробовать тройные апострофы
