### ISSUE TITLE
Как можно исключать файлы из проверки?

### ISSUE THREAD

**Issue by vbondarevsky** [1c-syntax/sonar-bsl-plugin-community#64]
Например, для проекта
https://sonar.openbsl.ru/dashboard?id=connector
хочу исключить из проверки тесты
src/DataProcessors/Тесты/*

**Comment by asosnoviy** [comment]
Поправлю вопрос немного. В сонаре можно указать папку с тестами, что должно измениться от этого?

**Comment by nixel2007** [comment]
Указать параметр sonar.exlusions.

Обратить внимание, что кириллица там должна писаться через \u000p

**Comment by asosnoviy** [comment]
Посмотрел немного в java плагине, там с тестами совсем отдельная история...

**Comment by KozinDV** [comment]
> Указать параметр sonar.exlusions.
> 
> Обратить внимание, что кириллица там должна писаться через \u0000

nixel2007, приведите, пожалуйста, пример написания кириллицы через \u0000.
Есть строки, как их записать корректно?

sonar.exclusions=\
	PR/src/CommonModules/АдминистрированиеКластера/Module.bsl,\
	PR/src/CommonModules/АдминистрированиеКластераКлиентСервер/Module.bsl,\
	PR/src/CommonModules/АдминистрированиеКластераCOM/Module.bsl,\
	PR/src/CommonModules/АдминистрированиеКластераCOMКлиентСервер/Module.bsl,\
	PR/src/CommonModules/АдминистрированиеКластераRAS/Module.bsl,\
	PR/src/CommonModules/АдминистрированиеКластераRASКлиентСервер/Module.bsl

Спасибо.

**Comment by nixel2007** [comment]
https://checkserp.com/encode/unicode/
