### ISSUE TITLE
Импорт цикломатической сложности

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/sonar-bsl-plugin-community#9]

**Comment by nixel2007** [comment]
Скорее импорт. Расчёт должен быть в lsp.

**Comment by asosnoviy** [comment]
Ага, машинально прировнял к cpd

**Comment by asosnoviy** [comment]
https://github.com/1c-syntax/bsl-language-server/issues/107

**Comment by theshadowco** [comment]
@asosnoviy, @nixel2007 
на меня повесьте
